# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5d01a1d045d4438e3baf0ba1205c18a33b1db3c89f3dc204b43a7a2d21273f05835703739f71b81d750884942c355e771f23812cb1b60adc4487ea9ca714e8f

test:
  secret_key_base: 610b2ccdd9d1c9024ecd1d32b8eb5665a4a969531e5c0b54a7e035a069c91665c3018067aa25b70e2c83da3a0c47e375783395ba6206fac6be89efc6f00b1761

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
